spring:
  application:
    name: cloud-movie-localhost
  datasource:
    initialize: true
    platform: h2 # scheme-XXXX 를 따라감
    url: jdbc:h2:mem:moviedb;
    username: sa
    password: null 
  h2:
    console:
      enabled: true
  session:
    store-type: none
logging:
  file: ../spring
  
name: 안뇽3
